## Задание 0 (из лекции)

In [1]:
import numpy as np

In [2]:
users_stats = np.array(
    [
        [2, 1, 0, 0, 0, 0],
        [1, 1, 2, 1, 0, 0],
        [2, 0, 1, 0, 0, 0],
        [1, 1, 2, 1, 0, 1],
        [0, 0, 1, 2, 0, 0],
        [0, 0, 0, 0, 0, 5],
        [1, 0, 0, 0, 0, 0],
        [0, 1, 1, 0, 0, 0],
        [0, 0, 0, 1, 1, 3],
        [1, 0, 0, 2, 1, 4]
    ], 
    np.int32
)

# На сайт заходит очередной посетитель, о покупках которого известно следующее:

next_user_stats = np.array([0, 1, 2, 0, 0, 0])

Найдите самого похожего пользователя. Т. е. посчитайте косинусное расстояние между этим пользователем и всеми пользователями из массива user_stats

In [3]:
def cosine( a, b ):
    """
    Подсчет косинуса угла между векторами a, b по их координатам
    """
    aLength = np.linalg.norm( a )
    bLength = np.linalg.norm( b )
    
    return np.dot( a, b ) / ( aLength * bLength )

user_id = [x for x in range(1, 11, 1)]
cos_list = []
for i in users_stats:
    cos_list.append((cosine( i, next_user_stats )))

similarity = dict(zip(user_id, cos_list))
solution = sorted(similarity.items(), key=lambda x: (x[1],x[0]), reverse=True)[0]
print(f'Наиболшее соответствие с user_id = {solution[0]}, косинусное растояние = {solution[1]}.')

Наиболшее соответствие с user_id = 8, косинусное растояние = 0.9486832980505138.


## Задание 1

Создайте numpy array с элементами от числа N до 0 (например, для N = 10 это будет array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])).

In [4]:
n = int(input('введите N:\n'))
np.linspace(n-1, 0, n)

введите N:
10


array([9., 8., 7., 6., 5., 4., 3., 2., 1., 0.])

## Задание 2

Создайте диагональную матрицу с элементами от N до 0. Посчитайте сумму ее значений на диагонали.

In [6]:
n = int(input('введите N:\n'))
my_matrix = np.diag(np.arange(n, 0, -1))
print(my_matrix)

def sum_diagonal(my_matrix):
    l = len(my_matrix)
    s = sum(my_matrix[i][i] for i in range(l))
    return s
print('Сумма по диогонали = ', sum_diagonal(my_matrix))

введите N:
10
[[10  0  0  0  0  0  0  0  0  0]
 [ 0  9  0  0  0  0  0  0  0  0]
 [ 0  0  8  0  0  0  0  0  0  0]
 [ 0  0  0  7  0  0  0  0  0  0]
 [ 0  0  0  0  6  0  0  0  0  0]
 [ 0  0  0  0  0  5  0  0  0  0]
 [ 0  0  0  0  0  0  4  0  0  0]
 [ 0  0  0  0  0  0  0  3  0  0]
 [ 0  0  0  0  0  0  0  0  2  0]
 [ 0  0  0  0  0  0  0  0  0  1]]
Сумма по диогонали =  55


## Задание 3

Решите систему уравнений:
* 4x + 2y + z = 4
* x + 3y = 12
* 5y + 4z = -3

In [15]:
from numpy import linalg
a = np.array( [ [4, 2, 1], [1, 3, 0], [0, 5, 4] ] )
r = np.array( [4, 12, -3] )
res = linalg.solve(a, r)
print(f'x = {res[0]}, y = {res[1]}, z = {res[2]}')

x = 0.4666666666666668, y = 3.844444444444444, z = -5.555555555555555
